name: Testes

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs: 
  build:
      runs-on: ubuntu-20.04

      steps:
        - name: Actions
        - uses: actions/checkout@v2

        - name: Use Node.js 16.13.2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.13.2
            cache: npm

        - name: Install modules
          run: npm ci

        - name: Run tests
          run: npm test