on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs: 
  ESlint: 
    runs-on: ubuntu-latest
  
    steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-node@v1
          with:
            node-version: 16.13.2
            cache: npm

        - name: Install modules
          run: npm ci

        - name: Run tests
          run: npm run lint 
  Testes:
      runs-on: ubuntu-20.04

      steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-node@v1
          with:
            node-version: 16.13.2
            cache: npm

        - name: Install modules
          run: npm ci

        - name: Run tests
          run: npm test