name: Testes

on:
  push:
  pull_request:
  workflow_dispatch:
jobs: 
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16.13.2
          cache: npm
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm test